version: '3.9'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: estudos-db
      # You can create a non-root user as well if desired:
      # MYSQL_USER: app
      # MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pexample"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: estudos-db
      DB_USER: root
      DB_PASSWORD: example
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
